research_task:
  description: >
    Conduct a thorough research about company {company}. Focus on {current_date}:
    0. Projected IPO value and stock price projections
    1. company status and health
    2. Historical company performance
    3. Major Challenges and opportunities
    4. Recent news and events
    5. Future outlook and potential developments.

    Make sure to organize your findings in a structured format with cleaar sections.
  expected_output: >
    A comprehensive research document with well-organized sections covering all the requested aspects of {company}.
    Include specific facts, figures, and examples where relevant.
  agent: researcher

analysis_task:
  description: >
    Analyze the research document and create a comprehensive report on {company}.
    The report should:
    1. Begin with an executive summary.

    2. include all key information from the research document. Specifically, Projected IPO value and stock price projections
    3. Provide insightful analysis of trends and patterns.
    4. Offer a market outlook for {company} noting that this should not be used for trading decisions.
    5. Be formatted in a professional, easy-to-read style with clear headings and subheadings.
  expected_output: >
    A polished, professional report on {company} that presents the research
    findings with added analysis and insights. The report should be well-structured
    with and executive summary, main sections, and conclusion.
  agent: analyst
  context:
    - research_task
  output_file: output/{company}_report.md
  